openapi: 3.0.0
info:
  title: Registration Portal API
  version: 1.0.0
  description: API Documentation for the Registration Portal
servers:
  - url: http://localhost:3000
tags:
  - name: auth
    description: Authentication related endpoints
  - name: users
    description: User related endpoints
  - name: application-responses
    description: Application responses related endpoints
paths:
  /api/auth/users:
    post:
      tags:
        - auth
      summary: Get a user's login details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@example.com
      responses:
        '200':
          description: Login details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users_auth'
  /api/auth/signup:
    post:
      tags:
        - auth
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: secret_password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email and password are required
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already exists
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to create user
  /api/users/{id}:
    get:
      tags:
        - users
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
  /api/users:
    post:
      tags:
        - users
      summary: Create a new user with fields in the users table
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '201':
          description: User created
  /api/application-responses/{id}:
    get:
      tags:
        - application-responses
      summary: Get an application response by user ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Application response details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application_responses'
  /api/application-responses:
    post:
      tags:
        - application-responses
      summary: Create a new application response in the application_responses table
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/application_responses'
      responses:
        '201':
          description: Application response created
components:
  schemas:
    users_auth:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
    users:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        age:
          type: integer
          minimum: 0
        email:
          type: string
        phone_number:
          type: string
        school:
          type: string
        level_of_study:
          type: string
        field_of_study:
          type: string
        country_of_residence:
          type: string
        address:
          type: string
        dietary_restrictions:
          type: string
        github:
          type: string
        linkedin:
          type: string
        personal_website:
          type: string
    application_responses:
      type: object
      properties:
        userid:
          type: integer
        q1:
          type: string
        q2:
          type: string
        q3:
          type: string
