openapi: 3.0.0
info:
  title: Registration Portal API
  version: 1.0.0
  description: API Documentation for the Registration Portal
servers:
  - url: http://localhost:3000
    description: Local server (would be replaced with production server URL)
paths:
  /api/users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        '404':
          description: The resource was not found
        '500':
          description: Internal Server Error

              
  /api/users:
    post:
      summary: Create a new user with fields in the users table
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users'
      responses:
        '201':
          description: User created

  /api/application-responses/{id}:
    get:
      summary: Get an application response by user ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Application response details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application_responses'
  /api/application-responses:
    post:
      summary: Create a new application response in the application_responses table
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/application_responses'
      responses:
        '201':
          description: Application response created

components:
  schemas:
    users:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for a user.
        firstname:
          type: string
          description: The user's first name.
        lastname:
          type: string
          description: The user's last name.
        age:
          type: integer
          minimum: 0
          description: The user's age. Must be a non-negative integer.
        email:
          type: string
          description: The user's email address.
        phone_number:
          type: string
          description: The user's telephone number (should we incorporate regular expression?).
        school:
          type: string
          description: The name of the school or university the user attends or attended.
        level_of_study:
          type: string
          description: The user's current level of study (e.g., undergraduate, graduate).
        field_of_study:
          type: string
          description: The user's major or primary field of study.
        country_of_residence:
          type: string
          description: The country in which the user currently resides.
        address:
          type: string
          description: The user's full mailing address.
        dietary_restrictions:
          type: string
          description: Any dietary restrictions the user has that should be considered at events.
        github:
          type: string
          description: The user's GitHub username or URL.
        linkedin:
          type: string
          description: The user's LinkedIn profile URL.
        personal_website:
          type: string
          description: URL to the user's personal or professional website.
        optional_underrepresented:
          type: string
          description: If the user identifies as part of an underrepresented group.
        optional_gender:
          type: string
          description: The gender identity of the user.
        optional_pronouns:
          type: string
          description: The pronouns the user prefers to be used in communication.
        optional_race:
          type: string
          description: The user's racial or ethnic background.
        optional_consider:
          type: string
          description: The question "do you consider yourself the following?"
        MLH_authorize:
          type: boolean
          description: Consent given by the user for Major League Hacking (MLH) to use their data (send email).
        resume:
          type: string
          format: uri
          description: A URL linking to the user's resume.
        t_shirt_size:
          type: string
          description: The user's t-shirt size (S, M, L, XL, etc.)
        other_dietary_restrictions:
          type: string
          description: Additional dietary restrictions not captured under 'dietary_restrictions'.

      required:
        - id
        - firstname
        - lastname
        - email
        - age
        - phone_number
        - school
        - level_of_study
        - field_of_study
        - country_of_residence
        - dietary_restrictions
    application_responses:
      type: object
      properties:
        userid:
          type: integer
        q1:
          type: string
        q2:
          type: string
        q3:
          type: string
