export const options = {
  ethnicities: [
    "Asian Indian",
    "Black or African",
    "Chinese",
    "Filipino",
    "Guamanian or Chamorro",
    "Hispanic / Latino / Spanish Origin",
    "Japanese",
    "Korean",
    "Middle Eastern",
    "Native American or Alaskan Native",
    "Native Hawaiian",
    "Samoan",
    "Vietnamese",
    "White",
    "Other Asian (Thai, Cambodian, etc)",
    "Other Pacific Islander",
    "Other (Please Specify)",
    "Prefer Not to Answer",
  ],
  levelsOfStudy: [
    "High School",
    "Undergraduate University (2 year - community college or similar)",
    "Undergraduate University (3+ year)",
    "Graduate University (Masters, Professional, Doctoral, etc)",
    "Code School / Bootcamp",
    "Other Vocational / Trade Program or Apprenticeship",
    "Post Doctorate",
    "Other",
    "Not a student",
    "Prefer not to answer",
  ],
  fieldsOfStudy: [
    "Computer science, computer engineering, or software engineering",
    "Another engineering discipline (such as civil, electrical, mechanical, etc.)",
    "Information systems, information technology, or system administration",
    "A natural science (such as biology, chemistry, physics, etc.)",
    "Mathematics or statistics",
    "Business discipline (such as accounting, finance, marketing, etc.)",
    "Humanities discipline (such as literature, history, philosophy, etc.)",
    "Social science (such as anthropology, psychology, political science, etc.)",
    "Fine arts or performing arts (such as graphic design, music, studio art, etc.)",
    "Health science (such as nursing, pharmacy, radiology, etc.)",
    "Undecided / No Declared Major",
  ],
  dietaryRestrictions: [
    "None",
    "Vegetarian",
    "Vegan",
    "Celiac Disease",
    "Kosher",
    "Halal",
  ],
  tShirtSizes: ["Small", "Medium", "Large", "Extra Large", "2XL"],
  underrepresented: ["Yes", "No", "Unsure"],
  genders: [
    "Man",
    "Woman",
    "Non-Binary",
    "Prefer to self-describe",
    "Prefer Not to Answer",
  ],
  pronouns: [
    "She/Her",
    "He/Him",
    "They/Them",
    "She/They",
    "He/They",
    "Prefer Not to Answer",
    "Other",
  ],
  sexualities: [
    "Heterosexual or straight",
    "Gay or lesbian",
    "Bisexual",
    "Different identity",
    "Prefer Not to Answer",
  ],
};

export const getAgeOptions = () => {
  return Array.from({ length: 27 }, (_, i) => i + 14);
};
